name: Deploy
on:
  workflow_dispatch:
    inputs:
      mode:
        description: Environment (prod)
        required: true
        default: prod

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: anime-skip/remote-config

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Build
        run: make build

  versioning:
    name: Bump Version
    if: ${{ github.event.inputs.mode == 'prod' }}
    runs-on: ubuntu-20.04
    needs: verify
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          ref: main
          fetch-depth: 0

      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: ./meta.json
          output-file: "false"

      - name: Don't deploy
        if: ${{ steps.changelog.outputs.skipped == 'true' }}
        run: |
          echo "No changes found, stopping deployment"
          exit 1

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-20.04
    needs: versioning
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Pull in Version Change
        run: git checkout main

      - name: Log into Heroku CLI
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ""
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Log into Heroku Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Log into Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build :prod
        run: |
          docker build . \
            -t docker.pkg.github.com/anime-skip/remote-config/app:prod \
            -t registry.heroku.com/prod-remote-config/web

      - name: Push :prod
        run: |
          docker push docker.pkg.github.com/anime-skip/remote-config/app:prod
          docker push registry.heroku.com/prod-remote-config/web

      - name: Deploy :prod
        run: |
          heroku container:release -a prod-remote-config web
